version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
      nodejs: 18
    commands:
      - echo Installing dependencies
      - yum update -y
      - yum install -y git
      - pip3 install --upgrade pip && pip3 install -r requirements.txt

  build:
    commands:
      - echo Build started on `date`
      - cd ./ui && CI=false && npm ci
      - npm run build:prod && cd ../ && ls

artifacts:
  files:
    - application.py
    - buildspec.yml
    - wsgi.py
    - requirements.txt
    - api/*.py
    - config/*.py
    - build/**/*
    - .ebextensions/*.conf
    - .platform/nginx/nginx.conf
  name: demo-app-artifacts
